import 'dart:io';

import 'package:flutter/foundation.dart';

import '../models/font_config.dart';

/// Number of fonts contained in a TrueType Collection (`.ttc`) file.
///
/// Returns 1 if the data is not a valid TTC (treat as a single font file).
int ttcFontCount(ByteData data) {
  if (data.lengthInBytes < 12) return 1;
  final tag = String.fromCharCodes([
    data.getUint8(0),
    data.getUint8(1),
    data.getUint8(2),
    data.getUint8(3),
  ]);
  if (tag != 'ttcf') return 1;
  return data.getUint32(8);
}

/// Returns true if [data] represents a font with TrueType (glyf) outlines,
/// which is the only format supported for embedded text by the `pdf` package.
///
/// Returns false for OpenType fonts with CFF (PostScript) outlines, whose
/// sfnt version is `'OTTO'`. CFF-flavored fonts cannot be embedded for use
/// with CJK / non-Latin text in PDFs generated by the `pdf` package.
bool isTrueTypeOutlineFont(ByteData data) {
  if (data.lengthInBytes < 4) return false;
  final sfnt = data.getUint32(0);
  // 0x00010000 = TrueType, 0x74727565 ('true') = legacy Apple TrueType.
  return sfnt == 0x00010000 || sfnt == 0x74727565;
}

/// Tables the `pdf` package requires in order to embed a TrueType font for
/// arbitrary (non-Latin) text via CID encoding. The package dereferences
/// these tables with `!`, so any one being absent crashes with a "Null check
/// operator used on a null value" deep inside `TtfWriter.withChars`.
const requiredPdfEmbeddingTables = <String>{
  'head',
  'hhea',
  'maxp',
  'hmtx',
  'cmap',
  'loca',
  'glyf',
  'name',
  'post',
  'OS/2',
};

/// List of sfnt table tags present in [data], parsed from the table
/// directory. Returns null if [data] does not look like an sfnt file.
Set<String>? listSfntTables(ByteData data) {
  if (data.lengthInBytes < 12) return null;
  final numTables = data.getUint16(4);
  final out = <String>{};
  for (var i = 0; i < numTables; i++) {
    final entry = 12 + i * 16;
    if (entry + 16 > data.lengthInBytes) return null;
    final tag = String.fromCharCodes([
      data.getUint8(entry),
      data.getUint8(entry + 1),
      data.getUint8(entry + 2),
      data.getUint8(entry + 3),
    ]);
    out.add(tag);
  }
  return out;
}

/// Returns the subset of [requiredPdfEmbeddingTables] missing from [data].
/// An empty set means the font has all required tables.
Set<String> missingPdfEmbeddingTables(ByteData data) {
  final present = listSfntTables(data);
  if (present == null) return requiredPdfEmbeddingTables;
  return requiredPdfEmbeddingTables.difference(present);
}

/// Extract a TrueType-outline (`glyf`) font from a TrueType Collection (.ttc)
/// that can be embedded by the `pdf` package.
///
/// Iterates through every font in the collection and returns the first one
/// whose sfnt version indicates TrueType outlines (skipping `'OTTO'` CFF
/// fonts) AND has all of the [requiredPdfEmbeddingTables]. Returns null if
/// no such font is found.
ByteData? extractFirstTrueTypeFromTtc(ByteData ttc) {
  final count = ttcFontCount(ttc);
  for (var i = 0; i < count; i++) {
    final extracted = extractTtfFromTtc(ttc, fontIndex: i);
    if (extracted == null) continue;
    if (!isTrueTypeOutlineFont(extracted)) continue;
    if (missingPdfEmbeddingTables(extracted).isNotEmpty) continue;
    return extracted;
  }
  return null;
}

/// Extract a single TTF font from a TrueType Collection (.ttc) file.
///
/// Returns null if the data is not a valid TTC or the [fontIndex] is out of
/// range.
ByteData? extractTtfFromTtc(ByteData ttc, {int fontIndex = 0}) {
  if (ttc.lengthInBytes < 12) return null;
  final tag = String.fromCharCodes([
    ttc.getUint8(0),
    ttc.getUint8(1),
    ttc.getUint8(2),
    ttc.getUint8(3),
  ]);
  if (tag != 'ttcf') return null;

  final numFonts = ttc.getUint32(8);
  if (fontIndex >= numFonts) return null;

  final fontOffset = ttc.getUint32(12 + fontIndex * 4);
  if (fontOffset + 12 > ttc.lengthInBytes) return null;

  final numTables = ttc.getUint16(fontOffset + 4);
  final tags = <int>[];
  final checksums = <int>[];
  final offsets = <int>[];
  final lengths = <int>[];
  for (var i = 0; i < numTables; i++) {
    final e = fontOffset + 12 + i * 16;
    if (e + 16 > ttc.lengthInBytes) return null;
    tags.add(ttc.getUint32(e));
    checksums.add(ttc.getUint32(e + 4));
    offsets.add(ttc.getUint32(e + 8));
    lengths.add(ttc.getUint32(e + 12));
  }

  final headerSize = 12 + numTables * 16;
  var totalSize = headerSize;
  for (final len in lengths) {
    totalSize += (len + 3) & ~3;
  }

  final out = ByteData(totalSize);

  // Bulk copy the sfnt header (12 bytes)
  final ttcBytes = ttc.buffer.asUint8List(ttc.offsetInBytes, ttc.lengthInBytes);
  out.buffer.asUint8List().setRange(0, 12, ttcBytes, fontOffset);

  var dataOffset = headerSize;
  for (var i = 0; i < numTables; i++) {
    final dirOff = 12 + i * 16;
    out.setUint32(dirOff, tags[i]);
    out.setUint32(dirOff + 4, checksums[i]);
    out.setUint32(dirOff + 8, dataOffset);
    out.setUint32(dirOff + 12, lengths[i]);
    // Bulk copy table data instead of byte-by-byte (~100x faster for large tables)
    out.buffer.asUint8List().setRange(
      dataOffset, dataOffset + lengths[i], ttcBytes, offsets[i],
    );
    dataOffset += (lengths[i] + 3) & ~3;
  }
  return out;
}

/// Parse the font family name from a TTF/OTF file's `name` table.
///
/// Returns the family name (nameID 1) using platformID 3 (Windows) with
/// UTF-16BE encoding first, falling back to platformID 1 (Mac) with
/// Latin/ASCII encoding. Returns null if the name cannot be parsed.
String? parseFontFamilyName(ByteData data) {
  if (data.lengthInBytes < 12) return null;

  final numTables = data.getUint16(4);
  int? nameTableOffset;
  int? nameTableLength;

  for (var i = 0; i < numTables; i++) {
    final entry = 12 + i * 16;
    if (entry + 16 > data.lengthInBytes) break;
    final tag = String.fromCharCodes([
      data.getUint8(entry),
      data.getUint8(entry + 1),
      data.getUint8(entry + 2),
      data.getUint8(entry + 3),
    ]);
    if (tag == 'name') {
      nameTableOffset = data.getUint32(entry + 8);
      nameTableLength = data.getUint32(entry + 12);
      break;
    }
  }

  if (nameTableOffset == null ||
      nameTableLength == null ||
      nameTableOffset + 6 > data.lengthInBytes) {
    return null;
  }

  final nameCount = data.getUint16(nameTableOffset + 2);
  final stringOffset = data.getUint16(nameTableOffset + 4);
  final stringsBase = nameTableOffset + stringOffset;

  String? windowsName;
  String? macName;

  for (var i = 0; i < nameCount; i++) {
    final rec = nameTableOffset + 6 + i * 12;
    if (rec + 12 > data.lengthInBytes) break;

    final platformID = data.getUint16(rec);
    final nameID = data.getUint16(rec + 6);
    final strLength = data.getUint16(rec + 8);
    final strOffset = data.getUint16(rec + 10);

    if (nameID != 1) continue; // only font family name

    final start = stringsBase + strOffset;
    if (start + strLength > data.lengthInBytes) continue;

    if (platformID == 3 && windowsName == null) {
      // Windows platform: UTF-16BE
      final chars = <int>[];
      for (var j = 0; j + 1 < strLength; j += 2) {
        chars.add(data.getUint16(start + j));
      }
      windowsName = String.fromCharCodes(chars).trim();
    } else if (platformID == 1 && macName == null) {
      // Macintosh platform: single-byte encoding (roughly Latin)
      final chars = <int>[];
      for (var j = 0; j < strLength; j++) {
        chars.add(data.getUint8(start + j));
      }
      macName = String.fromCharCodes(chars).trim();
    }

    if (windowsName != null) break;
  }

  final name = windowsName ?? macName;
  return (name != null && name.isNotEmpty) ? name : null;
}

/// Try to read the font family name from a file on disk.
///
/// Handles both plain TTF/OTF and TTC files (reads the first font in the
/// collection).
Future<String?> readFontFamilyName(String filePath) async {
  try {
    final file = File(filePath);
    final bytes = await file.readAsBytes();
    final data = ByteData.sublistView(bytes);

    // Check if TTC
    if (bytes.length >= 4 &&
        bytes[0] == 0x74 && // 't'
        bytes[1] == 0x74 && // 't'
        bytes[2] == 0x63 && // 'c'
        bytes[3] == 0x66) {
      // 'f'
      final ttf = extractTtfFromTtc(data, fontIndex: 0);
      if (ttf == null) return null;
      return parseFontFamilyName(ttf);
    }

    return parseFontFamilyName(data);
  } catch (e) {
    debugPrint('Failed to read font family name: $e');
    return null;
  }
}

/// Derive a human-readable name from a font file path, used as fallback when
/// the name table cannot be parsed.
String fontNameFromPath(String path) {
  // Handle both '/' (Unix) and '\' (Windows) path separators
  final lastSep = path.lastIndexOf(RegExp(r'[/\\]'));
  final fileName = lastSep >= 0 ? path.substring(lastSep + 1) : path;
  final dotIdx = fileName.lastIndexOf('.');
  return dotIdx > 0 ? fileName.substring(0, dotIdx) : fileName;
}

/// Resolve the effective [FontConfig] by checking project override first, then
/// app default, then a hardcoded fallback.
FontConfig effectiveFont(
  FontConfig? projectOverride,
  FontConfig? appDefault,
  FontConfig fallback,
) {
  return projectOverride ?? appDefault ?? fallback;
}

/// Convert a font size in points to preview pixels.
///
/// Based on the 3.78 px/mm conversion factor used in preview widgets
/// and the 72 DPI PDF coordinate system: pt / 72 * 25.4 * 3.78 ≈ pt * 1.333
double ptToPreviewPx = 1.333;

double previewFontSize(double fontSizePt) => fontSizePt * ptToPreviewPx;
